// import axios from 'axios';
import { ProductApiResponse } from '../types/api/productTypes';
import { getFavorites } from '../services/favoriteService';

// const API_URL = 'https://api.example.com/products';

const products: ProductApiResponse[] = [
    {
        id: '1',
        imageUrl: 'https://image.msscdn.net/images/goods_img/20210312/1841764/1841764_17104689185394_500.jpg',
        brandName: 'YALE',
        productName: '(24SS) 2 TONE ARCH T-SHIRT WHITE',
        price: 24,
        isNew: true,
        hashTags: ['yale', '2tone', 'arch', 'white'],
        category: 'tshirts',
        sex: 'women',
        onSale: true,
        onSalePrice: 20,
        availableColors: ['white'],
        availableSizes: ['s', 'm', 'l'],
    },
    {
        id: '2',
        imageUrl: 'https://image.msscdn.net/images/goods_img/20240415/4055771/4055771_17164413957204_500.png',
        brandName: 'DIMITRI BLACK',
        productName: '(VLAD) Pigment Slash Short-Sleeved T-Shirt_Charcoal',
        price: 28,
        isNew: false,
        hashTags: ['dimitri', 'pigment', 'slash', 'charcoal'],
        category: 'tshirts',
        sex: 'women',
        onSale: true,
        onSalePrice: 24,
        availableColors: ['charcoal', 'black'],
        availableSizes: ['s', 'm', 'l'],
    },
    {
        id: '3',
        imageUrl: 'https://image.msscdn.net/images/goods_img/20230310/3140760/3140760_17158257930573_500.jpg',
        brandName: 'URBANDTYPE',
        productName: 'Dayoff Graphic T-shirt_Red_DT395',
        price: 32,
        isNew: true,
        hashTags: ['urban', 'dayoff', 'graphic', 'red'],
        category: 'tshirts',
        sex: 'women',
        onSale: true,
        onSalePrice: 28,
        availableColors: ['red'],
        availableSizes: ['s', 'm', 'l'],
    },
    {
        id: '4',
        imageUrl: 'https://www.lostmanagementcities.com/web/product/medium/202306/078c1d191452d7c21d96d94332a4fc49.jpg',
        brandName: 'LMC',
        productName: 'PUMA X LMC GRAPHIC TEE White',
        price: 58,
        isNew: false,
        hashTags: ['puma', 'graphic', 'white'],
        category: 'tshirts',
        sex: 'men',
        onSale: true,
        onSalePrice: 50,
        availableColors: ['white'],
        availableSizes: ['s', 'm', 'l'],
    },
    {
        id: '5',
        imageUrl: 'https://www.lostmanagementcities.com/web/product/medium/202304/23699457d71598a8e5e386b7044b75c5.jpg',
        brandName: 'LMC',
        productName: 'OVERDYED COLLEGE BEAR TEE Cream',
        price: 15,
        isNew: true,
        hashTags: ['college', 'bear', 'overdye'],
        category: 'tshirts',
        sex: 'women',
        onSale: true,
        onSalePrice: 10,
        availableColors: ['cream'],
        availableSizes: ['s', 'm', 'l'],
    },
    {
        id: '6',
        imageUrl: 'https://www.lostmanagementcities.com/web/product/medium/202207/377a4b676b8372f4f49a90d9cac968f6.jpg',
        brandName: 'LMC',
        productName: 'LMC THORNS MULTI STRIPE TEE Black',
        price: 23,
        isNew: false,
        hashTags: ['thorns', 'multi', 'stripe'],
        category: 'tshirts',
        sex: 'men',
        onSale: true,
        onSalePrice: 20,
        availableColors: ['black'],
        availableSizes: ['s', 'm', 'l'],
    },
    {
        id: '7',
        imageUrl: 'https://cdn.shopify.com/s/files/1/0587/2605/6143/files/C-Logo-Tee-Green3_460x.jpg?v=1717490830',
        brandName: 'thisisneverthat',
        productName: 'C-Logo Tee',
        price: 70,
        isNew: true,
        hashTags: ['c', 'logo'],
        category: 'tshirts',
        sex: 'women',
        onSale: true,
        onSalePrice: 60,
        availableColors: ['green'],
        availableSizes: ['s', 'm', 'l'],
    },
    {
        id: '8',
        imageUrl: 'https://intl.thisisneverthat.com/cdn/shop/files/GD-Dancing-Bear-Mesh-S-S-Crew-Navy1_1080x.jpg?v=1716354023',
        brandName: 'thisisneverthat',
        productName: 'GD Dancing Bear Mesh S/S Crew Navy',
        price: 75,
        isNew: false,
        hashTags: ['dancing', 'bear'],
        category: 'tshirts',
        sex: 'men',
        onSale: true,
        onSalePrice: 60,
        availableColors: ['navy'],
        availableSizes: ['s', 'm', 'l'],
    },
    {
        id: '9',
        imageUrl: 'https://intl.thisisneverthat.com/cdn/shop/files/Two-Hounds-Tee-Sky-Blue1_1080x.jpg?v=1712653181',
        brandName: 'thisisneverthat',
        productName: 'Two Hounds Tee Sky Blue',
        price: 67,
        isNew: true,
        hashTags: ['two', 'hounds'],
        category: 'tshirts',
        sex: 'women',
        onSale: true,
        onSalePrice: 60,
        availableColors: ['skyblue'],
        availableSizes: ['s', 'm', 'l'],
    },
    {
        id: '10',
        imageUrl: 'https://intl.thisisneverthat.com/cdn/shop/files/DSN-Logo-Tee-BLACK5_1080x.jpg?v=1717490983',
        brandName: 'thisisneverthat',
        productName: 'DSN-Logo Tee Black',
        price: 80,
        isNew: false,
        hashTags: ['dsn', 'logo'],
        category: 'tshirts',
        sex: 'women',
        onSale: true,
        onSalePrice: 70,
        availableColors: ['black'],
        availableSizes: ['s', 'm', 'l'],
    },
];



export const fetchProducts = async (): Promise<ProductApiResponse[]> => {
    const favorites = getFavorites();

    return products.map(product => ({
        ...product,
        favorite: favorites.includes(product.id)
    }));
};
